"use client"

import "./page.css"
import { useState } from "react"
import { BookOpen, Check, ChevronDown, CircleHelp, Flame, Play, RotateCcw, Terminal, X } from "lucide-react"

const starter = `ember warmth = 7\nburn warmth`

export default function Home() {
  const [code, setCode] = useState(starter)
  const [compiled, setCompiled] = useState(false)
  const [showOutput, setShowOutput] = useState(true)

  function compile() { setCompiled(true); setShowOutput(true) }
  function reset() { setCode(starter); setCompiled(false); setShowOutput(true) }

  return <main className="app-shell">
    <header className="topbar">
      <div className="brand"><span className="brand-mark"><Flame size={18} fill="currentColor" /></span><span>embr</span><span className="brand-slash">/</span><span className="brand-sub">fire code</span></div>
      <nav className="topnav"><a className="active" href="#playground">Playground</a><a href="#docs"><BookOpen size={15}/> Docs</a><a href="https://github.com/princess38827/fire-code-embr" target="_blank" rel="noreferrer">Source</a></nav>
      <button className="help-btn" aria-label="Help"><CircleHelp size={18}/></button>
    </header>

    <section className="hero" id="playground">
      <div className="eyebrow"><span className="live-dot"/> LIVING EMBER · 0.1.0</div>
      <h1>Give your ideas<br/><em>a little heat.</em></h1>
      <p className="hero-copy">A tiny, provenance-aware language for expressing intent,<br className="desktop"/> preserving memory, and making things happen.</p>
      <div className="pipeline"><PipelineStep n="01" label="Source"/><span className="pipeline-line"/><PipelineStep n="02" label="Fire IR"/><span className="pipeline-line"/><PipelineStep n="03" label="Python"/></div>
    </section>

    <section className="workspace">
      <div className="workspace-head"><div><p className="section-kicker">TRY IT OUT</p><h2>Strike a spark</h2></div><div className="head-actions"><button className="ghost-btn" onClick={reset}><RotateCcw size={15}/> Reset</button><button className="compile-btn" onClick={compile}><Play size={14} fill="currentColor"/> Compile</button></div></div>
      <div className="editor-grid">
        <div className="editor-card"><div className="card-bar"><div className="window-dots"><span/><span/><span/></div><span className="file-name"><Terminal size={14}/> example.embr</span><span className="status-pill"><span/> Ready</span></div><div className="code-wrap"><div className="line-numbers">1<br/>2<br/>3<br/>4<br/>5<br/>6</div><textarea aria-label="Embr code editor" spellCheck={false} value={code} onChange={e => {setCode(e.target.value);setCompiled(false)}}/></div><div className="editor-footer"><span><span className="key-dot"/> UTF-8</span><span>Embr syntax</span></div></div>
        <div className={`output-card ${showOutput ? "" : "collapsed"}`}><div className="output-head"><div><span className="section-kicker">OUTPUT</span><strong>{compiled ? "Compiled successfully" : "Python backend"}</strong></div><button className="close-output" onClick={() => setShowOutput(false)} aria-label="Hide output"><X size={16}/></button></div>{showOutput && <><div className="success"><Check size={15}/><span>Validation passed · 2 instructions</span></div><pre><span className="comment"># generated by embr</span>{'\n'}warmth = 7{ '\n' }print(warmth)</pre><div className="runtime"><span>stdout</span><strong>{compiled ? "7" : "Waiting for compile..."}</strong></div></>}</div>
      </div>
      {!showOutput && <button className="reopen-btn" onClick={() => setShowOutput(true)}>Show output <ChevronDown size={14}/></button>}
    </section>

    <section className="principles" id="docs"><div className="principles-intro"><p className="section-kicker">THE EMBR PHILOSOPHY</p><h2>Small language.<br/><em>Deep roots.</em></h2><p>Every part of the pipeline knows where it came from. That means errors stay helpful and ideas stay yours.</p></div><div className="principle-list"><Principle icon="✦" title="Intent" text="Validation comes first. Nothing executes until it makes sense."/><Principle icon="↺" title="Memory" text="Name an ember once. Recall it whenever the moment is right."/><Principle icon="⌖" title="Provenance" text="Source spans travel with your code, from text to execution."/></div></section>
    <footer><span><Flame size={14}/> Made for curious minds</span><span>MIT License · Alana Sky</span></footer>
  </main>
}

function PipelineStep({n,label}:{n:string,label:string}) { return <div className="pipeline-step"><span>{n}</span><strong>{label}</strong></div> }
function Principle({icon,title,text}:{icon:string,title:string,text:string}) { return <article className="principle"><span className="principle-icon">{icon}</span><div><h3>{title}</h3><p>{text}</p></div></article> }
